[package]
name = "tests-mecall"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv-slic = { path = "../riscv-slic", features = ["mecall-backend"] }
riscv-rt = { workspace = true }
# hifive1 = { version = "0.13.0", features = ["board-redv"] }
hifive1 = { workspace = true }
panic-halt = "1.0.0"
