[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
runner = "qemu-system-riscv32 -machine sifive_e,revb=true -nographic -kernel"
# runner = "riscv64-unknown-elf-gdb -q -x gdb_init"
# runner = "probe-run --chip fe310-g002 --verbose"
rustflags = [
  "-C", "link-arg=-Thifive1-link.x",
    "--cfg", "portable_atomic_target_feature=\"zaamo\"",
]

[build]
target = "riscv32imc-unknown-none-elf"
